# Generated by Django 4.2.7 on 2026-09-27 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('old_type', models.CharField(blank=True, max_length=10, null=True)),
                ('new_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_type', models.CharField(blank=True, max_length=10, null=True)),
                ('reason', models.TextField()),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('management_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_adjustments', to='management.managementdetails')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
